from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import os

def make_report(image_filename, label, confidence, out_dir="reports"):
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, image_filename + "_report.pdf")
    c = canvas.Canvas(out_path, pagesize=letter)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 750, "AI Diagnosis Report")
    c.setFont("Helvetica", 12)
    c.drawString(50, 720, f"Image: {image_filename}")
    c.drawString(50, 700, f"Predicted Label: {label}")
    c.drawString(50, 680, f"Confidence: {confidence}")
    c.drawString(50, 640, "Note: This is a prototype report generated by the project demo.")
    c.save()
    return out_path
